import { Geist, Geist_Mono, Unbounded } from "next/font/google";
import "./globals.css";

export const unbounded = Unbounded({
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={unbounded.className}>
        <div>{children}</div>
      </body>
    </html>
  );
}
